### PR TITLE
Fix RLP encoding error

### LINKED ISSUE #740: Random RLP encoding failure
Brought in by #725

### PR DESCRIPTION
**Pull request by LLFourn**
Ethereum apparently expects that signature components do not start
with 0x00 (i.e be treated as RLP integers) Why? No body knows.

So we have to wrap the (R,s) values in U256s so they encode properly.

🤦

Fix #740.

### CODE REVIEW

File: application/comit_node/tests/ethereum_wallet/transaction.rs [hunk 1]
```diff
@@ -44,8 +44,8 @@ impl<'a> SignedTransaction<'a> {
 
 impl<'a> Encodable for SignedTransaction<'a> {
     fn rlp_append(&self, stream: &mut RlpStream) {
-        let r = &self.signature.0[0..32];
-        let s = &self.signature.0[32..64];
+        let r = U256::from(&self.signature.0[0..32]);
```
Comment (D4nte) [inline application/comit_node/tests/ethereum_wallet/transaction.rs]: ❌ as mentioned, please as add a comment 🤯

Comment (LLFourn) [reply application/comit_node/tests/ethereum_wallet/transaction.rs]: Done.
