### PR TITLE
Validate lnd invoice and payment against swap params

### LINKED ISSUE #2395: Validate lnd's Invoices/Payments against swap params
## Problem

Currently, we don't validate whether the invoice added or the payment made by the user matches what we told them to do.

## Goal

Fail early if the user doesn't do what we told them to in the action.
- Fail if the invoice (with the given hash) added has incorrect details
- Fail if the payment has incorrect details

## Ideas

Extend `halight::Params` with whatever you need to do appropriate validation inside the traits implemented on the lnd connectors. For example for an accepted payment (sender side): https://github.com/comit-network/comit-rs/blob/4fcb8b36b327ae8cc7225b80fa55a64fe6709970/cnd/src/lnd.rs#L221

### PR DESCRIPTION
**Pull request by rishflab**
Check whether the parameters specified in the invoice and payment
returned by lnd match the parameters specified in the swap
parameters. Remove fields from the invoice that are no being used.

Resolves #2395, #2430

### CODE REVIEW

File: cnd/src/swap_protocols/halight/connector.rs [hunk 1]
```diff
@@ -33,39 +38,77 @@ enum InvoiceState {
...
+    pub cltv_expiry: Timestamp,
     pub state: InvoiceState,
+    pub fallback_addr: ethereum::Address,
     #[serde(deserialize_with = "deserialize_r_preimage")]
     pub r_preimage: Option<[u8; 32]>,
 }
 
+impl ValidateParams for Invoice {
+    fn validate(self, params: halight::Params) -> Result<(), ValidationError> {
+        if params.lightning_cltv_expiry == self.cltv_expiry
```
Comment (rishflab) [inline cnd/src/swap_protocols/halight/connector.rs:76]: I am still not sure about these checks particularly the fallback_addr and lightning_amount

File: cnd/src/network.rs [hunk 2]
```diff
@@ -1181,7 +1183,7 @@ impl libp2p::swarm::NetworkBehaviourEventProcess<comit_ln::BehaviourOutEvent> fo
                             Role::Alice => {
                                 tokio::task::spawn({
                                     let lnd_connector: LndConnectorAsReceiver = (**lnd_connector_params).clone().into();
-                                    halight::new_halight_swap(local_swap_id, secret_hash, self.halight_states.clone(), lnd_connector)
+                                    halight::new_halight_swap(local_swap_id, secret_hash, Params::from(create_swap_params.clone()), self.halight_states.clone(), lnd_connector)
```
Comment (D4nte) [inline cnd/src/network.rs:1186]:
```suggestion
                                    halight::new_halight_swap(local_swap_id, secret_hash, create_swap_params.clone().into(), self.halight_states.clone(), lnd_connector)
```
Easier to read.

File: cnd/src/network.rs [hunk 3]
```diff
@@ -1216,7 +1218,7 @@ impl libp2p::swarm::NetworkBehaviourEventProcess<comit_ln::BehaviourOutEvent> fo
                             Role::Bob => {
                                 tokio::task::spawn({
                                     let lnd_connector: LndConnectorAsSender = (**lnd_connector_params).clone().into();
-                                    self::halight::new_halight_swap(local_swap_id, secret_hash, self.halight_states.clone(), lnd_connector)
+                                    self::halight::new_halight_swap(local_swap_id, secret_hash, Params::from(create_swap_params.clone()), self.halight_states.clone(), lnd_connector)
```
Comment (D4nte) [inline cnd/src/network.rs:1221]:
```suggestion
                                    self::halight::new_halight_swap(local_swap_id, secret_hash, create_swap_params.clone().into(), self.halight_states.clone(), lnd_connector)
```

File: cnd/src/swap_protocols/halight.rs [hunk 4]
```diff
@@ -243,7 +263,25 @@ where
...
+    pub lightning_cltv_expiry: Timestamp,
+    pub lightning_amount: asset::Bitcoin,
+}
+
+impl Params {
+    pub fn from(params: HanEtherereumHalightBitcoinCreateSwapParams) -> Self {
+        Params {
+            ethereum_identity: params.ethereum_identity,
+            ethereum_absolute_expiry: params.ethereum_absolute_expiry,
+            // ethereum_amount: params.ethereum_amount,
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight.rs:281]:
```suggestion
```

File: cnd/src/swap_protocols/halight/connector.rs [hunk 5]
```diff
@@ -33,39 +38,77 @@ enum InvoiceState {
...
+            && params.ethereum_identity == EthereumIdentity::from(self.fallback_addr)
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:77]:
```suggestion
```
We do not use the fallback address.

File: cnd/src/swap_protocols/halight/connector.rs [hunk 6]
```diff
@@ -33,39 +38,77 @@ enum InvoiceState {
...
+#[derive(Clone, Copy, Debug, Deserialize)]
+pub struct Invoice {
+    #[serde(deserialize_with = "deserialize_amount")]
+    pub value: asset::Bitcoin,
+    #[serde(deserialize_with = "deserialize_timestamp")]
+    pub expiry: Timestamp,
+    #[serde(deserialize_with = "deserialize_timestamp")]
+    pub cltv_expiry: Timestamp,
     pub state: InvoiceState,
+    pub fallback_addr: ethereum::Address,
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:69]: It is not possible to have an Ethereum Address on lnd.
```suggestion
```

File: cnd/src/swap_protocols/halight/connector.rs [hunk 7]
```diff
@@ -33,39 +38,77 @@ enum InvoiceState {
...
     #[serde(deserialize_with = "deserialize_r_preimage")]
     pub r_preimage: Option<[u8; 32]>,
 }
 
+impl ValidateParams for Invoice {
+    fn validate(self, params: halight::Params) -> Result<(), ValidationError> {
+        if params.lightning_cltv_expiry == self.cltv_expiry
+            && params.ethereum_identity == EthereumIdentity::from(self.fallback_addr)
+            && params.ethereum_absolute_expiry == self.expiry
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:78]:
```suggestion
```
`self.expiry` is the invoice's expiry. It is not (directly) related to the expiry on Ethereum.

File: cnd/src/swap_protocols/halight.rs [hunk 8]
```diff
@@ -243,7 +263,25 @@ where
...
-    pub secret_hash: SecretHash,
+    pub ethereum_identity: EthereumIdentity,
+    pub ethereum_absolute_expiry: Timestamp,
+    // pub ethereum_amount: asset::Ether,
+    pub lightning_identity: identity::Lightning,
+    pub lightning_cltv_expiry: Timestamp,
+    pub lightning_amount: asset::Bitcoin,
+}
+
+impl Params {
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight.rs:276]:
```suggestion
impl From<HanEtherereumHalightBitcoinCreateSwapParams> for Params {
```
Implement the `From` trait to have `Into` for free.

File: cnd/src/swap_protocols/halight/connector.rs [hunk 9]
```diff
@@ -94,7 +137,7 @@ impl LndConnectorParams {
 
 fn read_file<T>(path: PathBuf) -> anyhow::Result<T>
 where
-    T: TryFrom<Vec<u8>, Error = Error>,
+    T: TryFrom<Vec<u8>, Error = anyhow::Error>,
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:140]:
```suggestion
    T: TryFrom<Vec<u8>, Error = Error>,
```
`anyhow::Error` is already imported in this file.

File: cnd/src/swap_protocols/halight/connector.rs [hunk 10]
```diff
@@ -432,6 +513,56 @@ fn client(certificate: &Certificate, macaroon: &Macaroon) -> Result<reqwest::Cli
...
+where
+    D: Deserializer<'de>,
+{
+    struct Visitor;
+
+    impl<'de> de::Visitor<'de> for Visitor {
+        type Value = asset::Bitcoin;
+
+        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
+            formatter.write_str("a lightning r_preimage which is a base64 of an 32 byte array")
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:526]: This does not seem to be correct as we are deserialising a bitcoin asset here.

File: cnd/src/swap_protocols/halight/connector.rs [hunk 11]
```diff
@@ -432,6 +513,56 @@ fn client(certificate: &Certificate, macaroon: &Macaroon) -> Result<reqwest::Cli
     Ok(client)
 }
 
+pub fn deserialize_amount<'de, D>(deserializer: D) -> Result<asset::Bitcoin, D::Error>
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:516]: We already implemented this deserialisations somewhere else, can we try to re-use the code instead?

File: cnd/src/swap_protocols/halight/connector.rs [hunk 12]
```diff
@@ -432,6 +513,56 @@ fn client(certificate: &Certificate, macaroon: &Macaroon) -> Result<reqwest::Cli
...
+where
+    D: Deserializer<'de>,
+{
+    struct Visitor;
+
+    impl<'de> de::Visitor<'de> for Visitor {
+        type Value = Timestamp;
+
+        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
+            formatter.write_str("a lightning r_preimage which is a base64 of an 32 byte array")
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:551]: Copy-pasta

File: cnd/src/swap_protocols/halight/connector.rs [hunk 13]
```diff
@@ -490,6 +619,7 @@ mod tests {
 
         let invoice_json = r#"{
       "r_preimage": "FyNMCPE5nm96/QZUNXmFNzzDYYEaBtpXNcNe07bC+f8=",
+      "fallback_addr": "3MXqbMwf457U4Jaw35WnJdnL99mq7Q8oQQ",
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight/connector.rs:622]: We don't use the fallback address

File: cnd/src/swap_protocols/halight.rs [hunk 14]
```diff
@@ -243,7 +263,23 @@ where
     })
 }
 
-#[derive(Clone, Copy, Debug)]
+#[derive(Copy, Clone, Debug)]
 pub struct Params {
-    pub secret_hash: SecretHash,
+    pub ethereum_identity: EthereumIdentity,
+    pub ethereum_absolute_expiry: Timestamp,
```
Comment (thomaseizinger) [inline cnd/src/swap_protocols/halight.rs:269]: :mega: How are these two concerned with the halight protocol?

File: cnd/src/swap_protocols/halight.rs [hunk 15]
```diff
@@ -243,7 +263,23 @@ where
...
+    pub lightning_identity: identity::Lightning,
+    pub lightning_cltv_expiry: Timestamp,
+    pub lightning_amount: asset::Bitcoin,
```
Comment (thomaseizinger) [inline cnd/src/swap_protocols/halight.rs:272]: :mega: We are within the `halight` scope here, the `lightning_` prefix is just noise in this module.

File: cnd/src/swap_protocols/halight.rs [hunk 16]
```diff
@@ -243,7 +263,23 @@ where
...
+}
+
+impl From<HanEtherereumHalightBitcoinCreateSwapParams> for Params {
```
Comment (thomaseizinger) [inline cnd/src/swap_protocols/halight.rs:275]: :mega: If you want to do an impl like this, it shouldn't live in this module because you are creating a circular dependency here: The code that uses defines `HanEtherereumHalightBitcoinCreateSwapParams` also uses `Params` so both modules import from each other. Also `HanEtherereumHalightBitcoinCreateSwapParams` is not halight-specific but knows "more" about the codebase than this particular module.

File: cnd/src/swap_protocols/halight/connector.rs (hunk 11 above)
Comment (thomaseizinger) [reply cnd/src/swap_protocols/halight/connector.rs:511]: We haven't interacted with LN before so I wouldn't want to re-use API-specific code that just happens to be the same.
There is no super harmful duplication here as we just delegate to `from_sat` for the crucial part.
It is annoying that we have to do this, but if we want to avoid it then the solution shouldn't be: "just use the HTTP API serialization code".

File: cnd/src/swap_protocols/halight.rs [hunk 17]
```diff
@@ -243,7 +263,23 @@ where
     })
 }
 
-#[derive(Clone, Copy, Debug)]
+#[derive(Copy, Clone, Debug)]
 pub struct Params {
```
Comment (D4nte) [inline cnd/src/swap_protocols/halight.rs:267]: Looking at the usage of `halight::Params` I think it would make sense to add the secret hash to it as they are always used together.

```suggestion
pub struct Params {
	pub secret_hash: SecretHash,
```

File: cnd/src/swap_protocols/halight/connector.rs [hunk 18]
```diff
@@ -432,6 +508,56 @@ fn client(certificate: &Certificate, macaroon: &Macaroon) -> Result<reqwest::Cli
...
+where
+    D: Deserializer<'de>,
+{
+    struct Visitor;
+
+    impl<'de> de::Visitor<'de> for Visitor {
+        type Value = Timestamp;
+
+        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
+            formatter.write_str("a blocknumber as a string")
```
Comment (thomaseizinger) [inline cnd/src/swap_protocols/halight/connector.rs:546]: Is it actually a block number? I think it is seconds :thinking:

File: cnd/src/swap_protocols/halight/connector.rs (hunk 9 above)
Comment (thomaseizinger) [reply cnd/src/swap_protocols/halight/connector.rs]: I would actually prefer if we never import it because it makes it hard to know, which `Error` it is without jumping to the definition. `anyhow::Error` is still short and avoids any kind of ambiguity.

**Comment by tcharding** [comment]
Looks like the boys have got you covered on review for this one @rishflab, ping me if I'm needed please, otherwise I'll leave this one to them.

File: cnd/src/swap_protocols/halight.rs (hunk 16 above)
Comment (rishflab) [reply cnd/src/swap_protocols/halight.rs:275]: I had a look and only facade is importing halight. I cant see any circular dependency?

Comment (thomaseizinger) [reply cnd/src/swap_protocols/halight.rs:291]: Okay, forget the circular dependency talk :D
This `impl` deals with more than just halight (the current module) and should be defined in a different place IMO :)
Probably wherever `HanEtherereumHalightBitcoinCreateSwapParams` is defined makes the most sense!

You can see it as: conceptually, the halight module doesn't (and shouldn't) "know" in which swaps it is going to be involved. This is a concern of code that composes those modules together.

File: cnd/src/swap_protocols/halight.rs (hunk 17 above)
Comment (D4nte) [reply cnd/src/swap_protocols/halight.rs:285]: @rishflab not keen on this one?

Comment (thomaseizinger) [reply cnd/src/swap_protocols/halight.rs:285]: I agree with Franck here, for other connectors the secret hash is part of the params :)

**Comment by thomaseizinger** [comment]
@rishflab I fixed up the merge conflicts and pushed two follow-up commits that address some of the comments that were still open. Hope you find it useful :)
