### PR TITLE
Set CORS headers on error responses

### LINKED ISSUE #935: comit-rs does not set CORS headers for error responses
I just got an unexpected error in comit-i:
When sending an invalid request to the comit-node, I received: 

`Access to XMLHttpRequest at 'http://localhost:8000/swaps/rfc003' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` 

This means, the comit-node did not include the corresponding CORS header in the error response.

Since we are using the cors-module from `warp`, this is very likely an issue with `warp` and has to be fixed upstream.

Tasks:
- figure out if it is an upstream bug -> open a warp issue
- try to fix it in warp otherwise patch comit-rs
- make a dry-test

### PR DESCRIPTION
**Pull request by thomaseizinger**
Fixes #935.

### CODE REVIEW

File: api_tests/webgui/webgui.ts [hunk 1]
```diff
@@ -70,6 +70,18 @@ setTimeout(async function() {
             );
         });
 
+        it("[David] Sets appropriate CORS headers on error responses", async () => {
+            let res = await request(david.comit_node_url())
+                .get("/swaps/rfc003/deadbeef-dead-beef-dead-deadbeefdead")
+                .set("Origin", "http://localhost:8080");
+
+            res.should.have.status(404);
```
Comment (D4nte) [inline api_tests/webgui/webgui.ts]: 🤡  @thomaseizinger would comment "please use expect here".

Comment (thomaseizinger) [reply api_tests/webgui/webgui.ts]: Fair :D

Comment (thomaseizinger) [reply api_tests/webgui/webgui.ts]: I rewrote all assertions in `webgui` to use `expect`.
